### yaml file is "yet another markup language". It is like json,csv file etc
training_pipeline_config:
  pipeline_name: housing
  artifact_dir: artifact

data_ingestion_config:
  dataset_download_url: https://github.com/ageron/handson-ml/blob/master/datasets/housing/housing.tgz
  raw_data_dir: raw_data
  tgz_download_dir: tgz_data
  ingested_dir: ingested_data
  ingested_train_dir: train
  ingested_test_dir: test






data_validation_config:
  schema_file_name: schema.yaml


data_transformation_config:
  add_bedroom_per_room: true
  transformed_dir: transformed_data
  transformed_train_dir: train
  transformed_test_dir: test
  preprocessing_dir: preprocessed
  preprocessed_object_filepath: preprocessed.pkl


model_trainer_config:
  trained_model_dir: trained_model
  model_file_name: model.pkl
  base_accuracy: 0.6



model_evaluation_config:
  model_evaluation_file_name: model_evaluation.yaml


model_pusher_config:
  model_export_dir: saved_models